version: '2'
services:
  web:
    build: .
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:80"
    mem_limit: 1000000000
    memswap_limit: 2000000000
    environment:
      ALLOW_OVERRIDE: "true"
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: myapp