version: '2'
volumes:
  code:
services:
  web:
    build:
      context: ./code/
      dockerfile: Dockerfile-web
    image: hasmobi/gameportal/apache
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - code:/code
    environment:
      ALLOW_OVERRIDE: "true"
      mashapeKey: "C2k162btRUmshbmnbBZKYilNH7ebp1nMZGnjsngVL5jWfVPWcI"
      imgurClientId: "fb240b5dfff7c3c"
  migrations:
    build:
      context: ./code/
      dockerfile: Dockerfile-migrations
    image: hasmobi/gameportal/migrations
    depends_on:
      - web
    volumes_from:
      - web
  onetime_scrape:
    build:
      context: ./code/
      dockerfile: Dockerfile-onetime-scrape
    image: hasmobi/gameportal/onetime-scrape
    depends_on:
      - migrations
      - web
    volumes_from:
        - web
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: myapp