version: '2'
services:
  web:
    build:
      context: ./code/
      dockerfile: Dockerfile-web
    image: hasmobi/gameportal/apache
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      ALLOW_OVERRIDE: "true"
  migrations:
    build:
      context: ./code/
      dockerfile: Dockerfile-migrations
    depends_on:
      - web
  onetime_scrape:
    build:
      context: ./code/
      dockerfile: Dockerfile-onetime-scrape
    depends_on:
      - migrations
      - web
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: myapp