FROM hasmobi/gameportal/apache

#RUN chmod 755 /code/deploy.sh && chmod 755 /code/migrations.sh && bash /code/deploy.sh
#RUN chmod 755 /code/migrations.sh && bash /code/deploy.sh
RUN chmod 755 /code/scrape.sh

#ENTRYPOINT ["php", "/code/yii", "gamespot/scrape-coming-soon-games"]
ENTRYPOINT ["bash", "/code/scrape.sh"]